In [1]:
# Import neede libraries for EDA
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### ***Loading Data for vehicle dynamics on day 1***

In [2]:
# load the data
csv_path_1 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\md30_export_20251110.csv"
df1 = pd.read_csv(csv_path_1)

df1.head()

,id,ts,aplicom,lat,lon,hexdata,message_start,sender_id,receiver_id,message_id,...,surface_state,en15518_surface_state,grip,water_layer_thickness,ice_layer_thickness,snow_layer_thickness,unit_status_info,unit_error_bits,crc,geom
0,43509630,2025-11-10 01:50:38.942+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x3 0x36 0x0 0x44 0x0 0x90 0...,ab,1,0,20,...,3,3,0.697317,0.340409,0,0,9,8,8862,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
1,43509631,2025-11-10 01:50:38.945+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x4 0x36 0x0 0x44 0x0 0xA3 0...,ab,1,0,20,...,3,3,0.697985,0.337601,0,0,9,8,5d4b,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
2,43509632,2025-11-10 01:50:38.947+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x5 0x36 0x0 0x44 0x0 0xB7 0...,ab,1,0,20,...,3,3,0.695922,0.346411,0,0,9,8,c167,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
3,43509633,2025-11-10 01:50:38.949+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x6 0x36 0x0 0x44 0x0 0xCB 0...,ab,1,0,20,...,3,3,0.682641,0.413942,0,0,9,8,2af1,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
4,43509634,2025-11-10 01:50:38.95+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x7 0x36 0x0 0x44 0x0 0xDF 0...,ab,1,0,20,...,3,3,0.683389,0.409591,0,0,9,8,7647,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...

### ***Loading Data for vehicle dynamics on day 2***

In [3]:
csv_path_2 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\md30_export_20251127.csv"
df2 = pd.read_csv(csv_path_2)
df2.head()

,id,ts,aplicom,lat,lon,hexdata,message_start,sender_id,receiver_id,message_id,...,surface_state,en15518_surface_state,grip,water_layer_thickness,ice_layer_thickness,snow_layer_thickness,unit_status_info,unit_error_bits,crc,geom
0,47015103,2025-11-27 10:14:51.256+02,Aplicom A11 001,60.386148,23.106956,0xAB 0x1 0x0 0x20 0x0 0x36 0x0 0x44 0x0 0x3F 0...,ab,1,0,20,...,7,11,0.464402,0.0,0.085958,0.000990,9,8,887d,0101000020E6100000691CEA77611B374039B5334C6D31...
1,47015104,2025-11-27 10:14:51.345+02,Aplicom A11 001,60.386148,23.106955,0xAB 0x1 0x0 0x20 0x1 0x36 0x0 0x44 0x0 0x53 0...,ab,1,0,20,...,7,11,0.463235,0.0,0.086225,0.000991,9,8,7315,0101000020E6100000C8242367611B374039B5334C6D31...
2,47015105,2025-11-27 10:14:51.346+02,Aplicom A11 001,60.386148,23.106955,0xAB 0x1 0x0 0x20 0x2 0x36 0x0 0x44 0x0 0x66 0...,ab,1,0,20,...,7,11,0.462989,0.0,0.086281,0.000994,9,8,2fa6,0101000020E6100000C8242367611B374039B5334C6D31...
3,47015106,2025-11-27 10:14:51.741+02,Aplicom A11 001,60.386148,23.106955,0xAB 0x1 0x0 0x20 0x3 0x36 0x0 0x44 0x0 0x7A 0...,ab,1,0,20,...,7,11,0.463084,0.0,0.086260,0.000990,9,8,23b8,0101000020E6100000C8242367611B374039B5334C6D31...
4,47015107,2025-11-27 10:14:52.204+02,Aplicom A11 001,60.386148,23.106954,0xAB 0x1 0x0 0x20 0x4 0x36 0x0 0x44 0x0 0x8E 0...,ab,1,0,20,...,7,11,0.462395,0.0,0.086418,0.000985,9,8,e3ab,0101000020E6100000282D5C56611B374039B5334C6D31...

### ***Loading Data for vehicle dynamics on day 3***

In [4]:
csv_path_3 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\md30_export_20260109.csv"
df3 = pd.read_csv(csv_path_3)
df3.head()

,id,ts,aplicom,lat,lon,hexdata,message_start,sender_id,receiver_id,message_id,...,surface_state,en15518_surface_state,grip,water_layer_thickness,ice_layer_thickness,snow_layer_thickness,unit_status_info,unit_error_bits,crc,geom
0,54179124,2026-01-09 00:00:00.02+02,Aplicom A11 001,60.378603,23.594120,0xAB 0x1 0x0 0x20 0xA5 0x36 0x0 0x44 0x0 0xFC ...,ab,1,0,20,...,7,11,0.136738,0.0,0.287554,0.152802,9,8,c422,0101000020E610000047E6913F18983740709527107630...
1,54179125,2026-01-09 00:00:00.524+02,Aplicom A11 001,60.378603,23.594119,0xAB 0x1 0x0 0x20 0xA6 0x36 0x0 0x44 0x0 0x10 ...,ab,1,0,20,...,7,11,0.140446,0.0,0.281358,0.161008,9,8,8c2f,0101000020E6100000A6EECA2E18983740709527107630...
2,54179126,2026-01-09 00:00:01.021+02,Aplicom A11 001,60.378603,23.594119,0xAB 0x1 0x0 0x20 0xA7 0x36 0x0 0x44 0x0 0x24 ...,ab,1,0,20,...,7,11,0.138119,0.0,0.285162,0.155872,9,8,0470,0101000020E6100000A6EECA2E18983740709527107630...
3,54179127,2026-01-09 00:00:01.52+02,Aplicom A11 001,60.378603,23.594119,0xAB 0x1 0x0 0x20 0xA8 0x36 0x0 0x44 0x0 0x38 ...,ab,1,0,20,...,7,11,0.139221,0.0,0.283298,0.158163,9,8,b268,0101000020E6100000A6EECA2E18983740709527107630...
4,54179128,2026-01-09 00:00:02.021+02,Aplicom A11 001,60.378604,23.594119,0xAB 0x1 0x0 0x20 0xA9 0x36 0x0 0x44 0x0 0x4B ...,ab,1,0,20,...,7,11,0.139290,0.0,0.283283,0.158818,9,8,6502,0101000020E6100000A6EECA2E1898374041118B187630...

### ***Merge 3 DF and making one called "vehicle dynamics_df"***

In [5]:
# Concatenate the dataframes

vehicle_dynamics_df = pd.concat(
    [df1, df2, df3],
    ignore_index=True
)

vehicle_dynamics_df.head()

,id,ts,aplicom,lat,lon,hexdata,message_start,sender_id,receiver_id,message_id,...,surface_state,en15518_surface_state,grip,water_layer_thickness,ice_layer_thickness,snow_layer_thickness,unit_status_info,unit_error_bits,crc,geom
0,43509630,2025-11-10 01:50:38.942+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x3 0x36 0x0 0x44 0x0 0x90 0...,ab,1,0,20,...,3,3,0.697317,0.340409,0.0,0.0,9,8,8862,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
1,43509631,2025-11-10 01:50:38.945+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x4 0x36 0x0 0x44 0x0 0xA3 0...,ab,1,0,20,...,3,3,0.697985,0.337601,0.0,0.0,9,8,5d4b,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
2,43509632,2025-11-10 01:50:38.947+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x5 0x36 0x0 0x44 0x0 0xB7 0...,ab,1,0,20,...,3,3,0.695922,0.346411,0.0,0.0,9,8,c167,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
3,43509633,2025-11-10 01:50:38.949+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x6 0x36 0x0 0x44 0x0 0xCB 0...,ab,1,0,20,...,3,3,0.682641,0.413942,0.0,0.0,9,8,2af1,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
4,43509634,2025-11-10 01:50:38.95+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x7 0x36 0x0 0x44 0x0 0xDF 0...,ab,1,0,20,...,3,3,0.683389,0.409591,0.0,0.0,9,8,7647,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...

### ***Shape***

In [6]:
vehicle_dynamics_df.shape

(258260, 32)

### ***Describe***

In [7]:
vehicle_dynamics_df.describe()

,id,lat,lon,sender_id,receiver_id,message_id,message_number,data_length,interface_version,error_code,...,frost_point_temperature,surface_temperature,surface_state,en15518_surface_state,grip,water_layer_thickness,ice_layer_thickness,snow_layer_thickness,unit_status_info,unit_error_bits
count,2.582600e+05,258260.000000,258260.000000,258260.0,258260.0,258260.0,258260.000000,258260.0,258260.0,258260.0,...,258260.000000,258260.000000,258260.000000,258260.000000,258260.000000,258260.000000,258260.000000,258260.000000,258260.000000,258260.0
mean,4.848499e+07,60.265088,22.930954,1.0,0.0,20.0,127.554856,54.0,68.0,0.0,...,-1.831825,3.397858,4.510416,6.288345,0.458195,0.264400,0.187836,0.008751,230.287029,8.0
std,5.036458e+06,0.218707,0.498394,0.0,0.0,0.0,73.862923,0.0,0.0,0.0,...,10.354134,9.375059,2.425369,4.377362,0.305384,0.540065,0.281561,0.019997,2683.638710,0.0
min,4.350963e+07,59.810994,22.097000,1.0,0.0,20.0,0.000000,54.0,68.0,0.0,...,-18.656288,-12.790009,1.000000,1.000000,0.100000,0.000000,0.000000,0.000000,9.000000,8.0
25%,4.363887e+07,60.052504,22.657507,1.0,0.0,20.0,64.000000,54.0,68.0,0.0,...,-14.056466,-6.549988,3.000000,2.000000,0.111460,0.000000,0.000000,0.000000,9.000000,8.0
50%,4.704149e+07,60.386083,23.017695,1.0,0.0,20.0,128.000000,54.0,68.0,0.0,...,3.076620,8.329987,3.000000,3.000000,0.589202,0.000000,0.000000,0.000000,9.000000,8.0
75%,5.426199e+07,60.442570,23.293149,1.0,0.0,20.0,191.000000,54.0,68.0,0.0,...,7.246938,11.510010,7.000000,11.000000,0.747730,0.306703,0.359613,0.002213,9.000000,8.0
max,5.437900e+07,60.502931,23.856204,1.0,0.0,20.0,255.000000,54.0,68.0,0.0,...,13.089999,18.589996,9.000000,11.000000,0.820000,34.550064,5.989631,0.456458,32781.000000,8.0

### ***Check for NaN***

In [8]:
vehicle_dynamics_df.isna().sum()

id                         0
ts                         0
aplicom                    0
lat                        0
lon                        0
hexdata                    0
message_start              0
sender_id                  0
receiver_id                0
message_id                 0
message_number             0
data_length                0
interface_version          0
error_code                 0
data_analyze_count         0
data_status_warning        0
data_status_error          0
air_temperature            0
relative_humidity          0
dew_point_temperature      0
frost_point_temperature    0
surface_temperature        0
surface_state              0
en15518_surface_state      0
grip                       0
water_layer_thickness      0
ice_layer_thickness        0
snow_layer_thickness       0
unit_status_info           0
unit_error_bits            0
crc                        0
geom                       0
dtype: int64

### ***new DF***

In [10]:
vehicle_dynamics_df.head()

,id,ts,aplicom,lat,lon,hexdata,message_start,sender_id,receiver_id,message_id,...,surface_state,en15518_surface_state,grip,water_layer_thickness,ice_layer_thickness,snow_layer_thickness,unit_status_info,unit_error_bits,crc,geom
0,43509630,2025-11-10 01:50:38.942+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x3 0x36 0x0 0x44 0x0 0x90 0...,ab,1,0,20,...,3,3,0.697317,0.340409,0.0,0.0,9,8,8862,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
1,43509631,2025-11-10 01:50:38.945+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x4 0x36 0x0 0x44 0x0 0xA3 0...,ab,1,0,20,...,3,3,0.697985,0.337601,0.0,0.0,9,8,5d4b,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
2,43509632,2025-11-10 01:50:38.947+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x5 0x36 0x0 0x44 0x0 0xB7 0...,ab,1,0,20,...,3,3,0.695922,0.346411,0.0,0.0,9,8,c167,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
3,43509633,2025-11-10 01:50:38.949+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x6 0x36 0x0 0x44 0x0 0xCB 0...,ab,1,0,20,...,3,3,0.682641,0.413942,0.0,0.0,9,8,2af1,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...
4,43509634,2025-11-10 01:50:38.95+02,Aplicom A11 001,60.493152,22.288015,0xAB 0x1 0x0 0x20 0x7 0x36 0x0 0x44 0x0 0xDF 0...,ab,1,0,20,...,3,3,0.683389,0.409591,0.0,0.0,9,8,7647,0101000020E6100000E8C1DD59BB4936407FFACF9A1F3F...

### ***check for unique data***

In [19]:
vehicle_dynamics_df["aplicom"].nunique()

1

### ***check for Duplicates***

No Duplicates

In [20]:
vehicle_dynamics_df.duplicated().sum()

np.int64(0)

### ***check for DatTypes***

We have Numeric & String Data. On the other hand we dont have any categorical data also

In [21]:
pd.DataFrame(vehicle_dynamics_df.dtypes, columns=['Data Type'])

                        Data Type
id                          int64
ts                            str
aplicom                       str
lat                       float64
lon                       float64
hexdata                       str
message_start                 str
sender_id                   int64
receiver_id                 int64
message_id                  int64
message_number              int64
data_length                 int64
interface_version           int64
error_code                  int64
data_analyze_count          int64
data_status_warning         int64
data_status_error           int64
air_temperature           float64
relative_humidity         float64
dew_point_temperature     float64
frost_point_temperature   float64
surface_temperature       float64
surface_state               int64
en15518_surface_state       int64
grip                      float64
water_layer_thickness     float64
ice_layer_thickness       float64
snow_layer_thickness      float64
unit_status_info            int64
unit_error_bits             int64
crc                           str
geom                          str