In [1]:
# Import neede libraries for EDA
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### ***Loading Data for GPS on day 1***

In [2]:
# load the data
csv_path_1 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\g_data_export_20251110.csv"
df1 = pd.read_csv(csv_path_1)

df1.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615026,2025-11-10 01:48:05.187+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-86,0201061bff9904050512ffffffff02a4fd0cfffc7e9655...,60.493215,22.287981,...,676,-756,-4,2.612,4,85,7383,-36.640755,3.639896,2.106111
1,18615027,2025-11-10 01:48:07.15+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-79,0201061bff9904050511ffffffff02a4fd14fff87e9655...,60.493212,22.287982,...,676,-748,-8,2.612,4,85,7384,-41.093213,8.394061,8.235836
2,18615028,2025-11-10 01:48:09.034+02,NaN,Aplicom A11 001,499,E198DBE2771E,-85,0201061bff9904050530ffffffff03dcfe8cfff074f668...,60.493206,22.287980,...,988,-372,-16,2.535,4,104,7184,-4.469715,42.277061,-1.047282
3,18615033,2025-11-10 01:48:20.72+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-81,0201061bff9904050511ffffffff02a0fd0cfffc7e9655...,60.493177,22.288002,...,672,-756,-4,2.612,4,85,7389,-36.175016,0.671586,4.746608
4,18615034,2025-11-10 01:48:23.017+02,NaN,Aplicom A11 001,499,E198DBE2771E,-84,0201061bff9904050530ffffffff03dcfe94ffec74f668...,60.493175,22.288007,...,988,-364,-20,2.535,4,104,7189,-6.271060,50.472670,2.049030

### ***Loading Data for GPS on day 2***

In [3]:
csv_path_2 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\g_data_export_20251127.csv"
df2 = pd.read_csv(csv_path_2)
df2.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,19073449,2025-11-27 00:00:05.695+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-87,0201061bff990405fbd6ffffffff0274fd18003470f6f6...,60.197226,23.695725,...,628,-744,52,2.503,4,246,52104,23.731888,-16.938574,41.037724
1,19073450,2025-11-27 00:02:15.075+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405fbcfffffffff022cfd7c00047176e6...,60.210708,23.660503,...,556,-644,4,2.507,4,230,52154,-21.557863,-10.685918,165.125365
2,19073451,2025-11-27 00:03:18.962+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-93,0201061bff990405fbeeffffffff0290fdbcffac71d649...,60.215488,23.638391,...,656,-580,-84,2.510,4,73,52179,-124.335487,94.410635,149.911073
3,19073452,2025-11-27 00:05:26.44+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405fbefffffffff02acfcb4ffd87176f9...,60.232282,23.607309,...,684,-844,-40,2.507,4,249,52229,-67.901596,-52.925755,-68.087101
4,19073453,2025-11-27 00:06:14.015+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-90,0201061bff990405fbfaffffffff025cfd10fffc70163a...,60.234494,23.589772,...,604,-752,-4,2.496,4,58,52248,-28.501015,-47.157435,52.637050

### ***Loading Data for GPS on day 3***

In [4]:
csv_path_3 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\g_data_export_20260109.csv"
df3 = pd.read_csv(csv_path_3)
df3.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,20043979,2026-01-09 00:06:10.854+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-87,0201061bff990405f37affffffff02c4fd2000086136de...,60.390492,23.577790,...,708,-736,8,2.377,4,222,56090,-29.688556,42.078561,-4.385111
1,20043980,2026-01-09 00:06:57.334+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405f37affffffff02dcfcc0ffc45d362c...,60.392027,23.559964,...,732,-832,-60,2.345,4,44,56108,-94.047775,-11.960919,-90.138394
2,20043981,2026-01-09 00:06:58.861+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405f378ffffffff02acfd08ffac5d3632...,60.392055,23.559383,...,684,-760,-84,2.345,4,50,56109,-116.635061,-3.262178,-3.662118
3,20043982,2026-01-09 00:08:24.204+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-88,0201061bff990405f37affffffff02b0fd8c00105f76d7...,60.391609,23.526509,...,688,-628,16,2.363,4,215,56142,-26.005580,99.328246,89.619725
4,20044343,2026-01-09 00:09:21.9+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-89,0201061bff990405f377ffffffff0260fcb0ffa45d9641...,60.387343,23.505953,...,608,-848,-92,2.348,4,65,56164,-110.358135,-118.590075,-19.285058

### ***Merge 3 DF and making one called "gps_df"***

In [5]:
# Concatenate the dataframes

gps_df = pd.concat(
    [df1, df2, df3],
    ignore_index=True
)

gps_df.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615026,2025-11-10 01:48:05.187+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-86,0201061bff9904050512ffffffff02a4fd0cfffc7e9655...,60.493215,22.287981,...,676,-756,-4,2.612,4,85,7383,-36.640755,3.639896,2.106111
1,18615027,2025-11-10 01:48:07.15+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-79,0201061bff9904050511ffffffff02a4fd14fff87e9655...,60.493212,22.287982,...,676,-748,-8,2.612,4,85,7384,-41.093213,8.394061,8.235836
2,18615028,2025-11-10 01:48:09.034+02,NaN,Aplicom A11 001,499,E198DBE2771E,-85,0201061bff9904050530ffffffff03dcfe8cfff074f668...,60.493206,22.287980,...,988,-372,-16,2.535,4,104,7184,-4.469715,42.277061,-1.047282
3,18615033,2025-11-10 01:48:20.72+02,NaN,Aplicom A11 001,499,E78E9C0B06E0,-81,0201061bff9904050511ffffffff02a0fd0cfffc7e9655...,60.493177,22.288002,...,672,-756,-4,2.612,4,85,7389,-36.175016,0.671586,4.746608
4,18615034,2025-11-10 01:48:23.017+02,NaN,Aplicom A11 001,499,E198DBE2771E,-84,0201061bff9904050530ffffffff03dcfe94ffec74f668...,60.493175,22.288007,...,988,-364,-20,2.535,4,104,7189,-6.271060,50.472670,2.049030

### ***Shape***

In [6]:
gps_df.shape

(26277, 22)

### ***Describe***

In [7]:
gps_df.describe()

,id,ruuvi,companyid,rssi,lat,lon,temperature,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
count,2.627700e+04,0.0,26277.0,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000,26277.000000
mean,1.913329e+07,NaN,499.0,-87.424782,60.352387,22.924812,211.198349,720.812117,-621.705446,-3.796590,2.464330,3.999924,159.297941,38733.575294,-14.532110,22.321338,6.509531
std,4.615146e+05,NaN,0.0,2.332945,0.145720,0.469647,150.138414,327.647615,239.660314,45.019964,0.127866,0.012338,57.525503,21156.765732,59.777474,94.874305,56.664210
min,1.861503e+07,NaN,499.0,-95.000000,59.819417,22.097018,0.150000,-984.000000,-2040.000000,-1128.000000,2.004000,2.000000,0.000000,8.000000,-1115.062094,-555.080147,-1123.722275
25%,1.864285e+07,NaN,499.0,-89.000000,60.386161,22.722653,7.680000,664.000000,-752.000000,-16.000000,2.366000,4.000000,133.000000,14793.000000,-28.086167,2.040744,0.865146
50%,1.908322e+07,NaN,499.0,-88.000000,60.386185,23.106952,316.445000,676.000000,-744.000000,0.000000,2.507000,4.000000,186.000000,53832.000000,-16.126246,10.229383,6.616960
75%,1.910004e+07,NaN,499.0,-86.000000,60.445180,23.107016,323.440000,988.000000,-368.000000,16.000000,2.549000,4.000000,193.000000,57022.000000,6.485598,52.171356,12.762402
max,2.006978e+07,NaN,499.0,-67.000000,60.502904,23.852558,326.235000,1596.000000,16494.000000,2825.000000,2.672000,4.000000,254.000000,65470.000000,7031.991503,14202.277312,6519.375053

### ***Check for NaN***

In [8]:
gps_df.isna().sum()

id                     0
ts                     0
ruuvi              26277
aplicom                0
companyid              0
address                0
rssi                   0
advdata                0
lat                    0
lon                    0
geom                   0
temperature            0
accx                   0
accy                   0
accz                   0
battvoltage            0
txpower                0
movcounter             0
measseqnum             0
calibrated_accx        0
calibrated_accy        0
calibrated_accz        0
dtype: int64

### ***lets drop "ruuvi" and see the shape***

In [9]:
# drop advdata column
gps_df1 = gps_df.drop(columns=['ruuvi'])
gps_df1.shape

(26277, 21)

### ***new DF***

In [10]:
gps_df1.head()

,id,ts,aplicom,companyid,address,rssi,advdata,lat,lon,geom,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615026,2025-11-10 01:48:05.187+02,Aplicom A11 001,499,E78E9C0B06E0,-86,0201061bff9904050512ffffffff02a4fd0cfffc7e9655...,60.493215,22.287981,0101000020E61000008FDE701FB9493640C5724BAB213F...,...,676,-756,-4,2.612,4,85,7383,-36.640755,3.639896,2.106111
1,18615027,2025-11-10 01:48:07.15+02,Aplicom A11 001,499,E78E9C0B06E0,-79,0201061bff9904050511ffffffff02a4fd14fff87e9655...,60.493212,22.287982,0101000020E610000030D63730B949364054FF2092213F...,...,676,-748,-8,2.612,4,85,7384,-41.093213,8.394061,8.235836
2,18615028,2025-11-10 01:48:09.034+02,Aplicom A11 001,499,E198DBE2771E,-85,0201061bff9904050530ffffffff03dcfe8cfff074f668...,60.493206,22.287980,0101000020E6100000EFE6A90EB94936407218CC5F213F...,...,988,-372,-16,2.535,4,104,7184,-4.469715,42.277061,-1.047282
3,18615033,2025-11-10 01:48:20.72+02,Aplicom A11 001,499,E78E9C0B06E0,-81,0201061bff9904050511ffffffff02a0fd0cfffc7e9655...,60.493177,22.288002,0101000020E6100000BE2EC37FBA493640D811876C203F...,...,672,-756,-4,2.612,4,85,7389,-36.175016,0.671586,4.746608
4,18615034,2025-11-10 01:48:23.017+02,Aplicom A11 001,499,E198DBE2771E,-84,0201061bff9904050530ffffffff03dcfe94ffec74f668...,60.493175,22.288007,0101000020E6100000E204A6D3BA493640371AC05B203F...,...,988,-364,-20,2.535,4,104,7189,-6.271060,50.472670,2.049030

### ***check for Duplicates***

No Duplicates

In [11]:
gps_df1.duplicated().sum()

np.int64(0)

### ***check for DatTypes***

In [12]:
pd.DataFrame(gps_df1.dtypes, columns=['Data Type'])

                Data Type
id                  int64
ts                    str
aplicom               str
companyid           int64
address               str
rssi                int64
advdata               str
lat               float64
lon               float64
geom                  str
temperature       float64
accx                int64
accy                int64
accz                int64
battvoltage       float64
txpower             int64
movcounter          int64
measseqnum          int64
calibrated_accx   float64
calibrated_accy   float64
calibrated_accz   float64

In [13]:
gps_df1.head()

,id,ts,aplicom,companyid,address,rssi,advdata,lat,lon,geom,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615026,2025-11-10 01:48:05.187+02,Aplicom A11 001,499,E78E9C0B06E0,-86,0201061bff9904050512ffffffff02a4fd0cfffc7e9655...,60.493215,22.287981,0101000020E61000008FDE701FB9493640C5724BAB213F...,...,676,-756,-4,2.612,4,85,7383,-36.640755,3.639896,2.106111
1,18615027,2025-11-10 01:48:07.15+02,Aplicom A11 001,499,E78E9C0B06E0,-79,0201061bff9904050511ffffffff02a4fd14fff87e9655...,60.493212,22.287982,0101000020E610000030D63730B949364054FF2092213F...,...,676,-748,-8,2.612,4,85,7384,-41.093213,8.394061,8.235836
2,18615028,2025-11-10 01:48:09.034+02,Aplicom A11 001,499,E198DBE2771E,-85,0201061bff9904050530ffffffff03dcfe8cfff074f668...,60.493206,22.287980,0101000020E6100000EFE6A90EB94936407218CC5F213F...,...,988,-372,-16,2.535,4,104,7184,-4.469715,42.277061,-1.047282
3,18615033,2025-11-10 01:48:20.72+02,Aplicom A11 001,499,E78E9C0B06E0,-81,0201061bff9904050511ffffffff02a0fd0cfffc7e9655...,60.493177,22.288002,0101000020E6100000BE2EC37FBA493640D811876C203F...,...,672,-756,-4,2.612,4,85,7389,-36.175016,0.671586,4.746608
4,18615034,2025-11-10 01:48:23.017+02,Aplicom A11 001,499,E198DBE2771E,-84,0201061bff9904050530ffffffff03dcfe94ffec74f668...,60.493175,22.288007,0101000020E6100000E204A6D3BA493640371AC05B203F...,...,988,-364,-20,2.535,4,104,7189,-6.271060,50.472670,2.049030

### ***check for features more***

In [14]:
gps_df1["aplicom"].nunique()

1

In [15]:
gps_df1["companyid"].nunique()

1

In [16]:
gps_df1["address"].nunique()

3

In [18]:
gps_df1["txpower"].nunique()

2

### ***lets remove all features where unique values = 1 for now***

In [19]:
## REmove aplicom, companyid for now
gps_df2 = gps_df1.drop(columns=['aplicom', 'companyid'])

In [20]:
gps_df2.head()

,id,ts,address,rssi,advdata,lat,lon,geom,temperature,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615026,2025-11-10 01:48:05.187+02,E78E9C0B06E0,-86,0201061bff9904050512ffffffff02a4fd0cfffc7e9655...,60.493215,22.287981,0101000020E61000008FDE701FB9493640C5724BAB213F...,6.490,676,-756,-4,2.612,4,85,7383,-36.640755,3.639896,2.106111
1,18615027,2025-11-10 01:48:07.15+02,E78E9C0B06E0,-79,0201061bff9904050511ffffffff02a4fd14fff87e9655...,60.493212,22.287982,0101000020E610000030D63730B949364054FF2092213F...,6.485,676,-748,-8,2.612,4,85,7384,-41.093213,8.394061,8.235836
2,18615028,2025-11-10 01:48:09.034+02,E198DBE2771E,-85,0201061bff9904050530ffffffff03dcfe8cfff074f668...,60.493206,22.287980,0101000020E6100000EFE6A90EB94936407218CC5F213F...,6.640,988,-372,-16,2.535,4,104,7184,-4.469715,42.277061,-1.047282
3,18615033,2025-11-10 01:48:20.72+02,E78E9C0B06E0,-81,0201061bff9904050511ffffffff02a0fd0cfffc7e9655...,60.493177,22.288002,0101000020E6100000BE2EC37FBA493640D811876C203F...,6.485,672,-756,-4,2.612,4,85,7389,-36.175016,0.671586,4.746608
4,18615034,2025-11-10 01:48:23.017+02,E198DBE2771E,-84,0201061bff9904050530ffffffff03dcfe94ffec74f668...,60.493175,22.288007,0101000020E6100000E204A6D3BA493640371AC05B203F...,6.640,988,-364,-20,2.535,4,104,7189,-6.271060,50.472670,2.049030

### ***lets remove more unwanted features like transmission pover, battery voltage advertisement payload***

In [21]:
## REmove battvoltage, advdata, txpower as well
gps_df2 = gps_df2.drop(columns=['battvoltage', 'advdata', 'txpower'])

In [22]:
gps_df2.head()

,id,ts,address,rssi,lat,lon,geom,temperature,accx,accy,accz,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615026,2025-11-10 01:48:05.187+02,E78E9C0B06E0,-86,60.493215,22.287981,0101000020E61000008FDE701FB9493640C5724BAB213F...,6.490,676,-756,-4,85,7383,-36.640755,3.639896,2.106111
1,18615027,2025-11-10 01:48:07.15+02,E78E9C0B06E0,-79,60.493212,22.287982,0101000020E610000030D63730B949364054FF2092213F...,6.485,676,-748,-8,85,7384,-41.093213,8.394061,8.235836
2,18615028,2025-11-10 01:48:09.034+02,E198DBE2771E,-85,60.493206,22.287980,0101000020E6100000EFE6A90EB94936407218CC5F213F...,6.640,988,-372,-16,104,7184,-4.469715,42.277061,-1.047282
3,18615033,2025-11-10 01:48:20.72+02,E78E9C0B06E0,-81,60.493177,22.288002,0101000020E6100000BE2EC37FBA493640D811876C203F...,6.485,672,-756,-4,85,7389,-36.175016,0.671586,4.746608
4,18615034,2025-11-10 01:48:23.017+02,E198DBE2771E,-84,60.493175,22.288007,0101000020E6100000E204A6D3BA493640371AC05B203F...,6.640,988,-364,-20,104,7189,-6.271060,50.472670,2.049030