In [1]:
# Import neede libraries for EDA
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### ***Loading Data for button press on day 1***

In [2]:
# load the data
csv_path_1 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\flic_button_data_export_20251110.csv"
df1 = pd.read_csv(csv_path_1)

df1.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615183,2025-11-10 01:50:40.22+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-60,NaN,60.493152,22.288016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18615186,2025-11-10 01:50:42.122+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-63,NaN,60.493151,22.288017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,18615187,2025-11-10 01:50:44.1+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-76,NaN,60.493150,22.288017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18615189,2025-11-10 01:50:45.963+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-55,NaN,60.493148,22.288014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18615192,2025-11-10 01:50:48.722+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-54,NaN,60.493146,22.288012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### ***Loading Data for button press on day 2***

In [3]:
csv_path_2 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\flic_button_data_export_20251127.csv"
df2 = pd.read_csv(csv_path_2)
df2.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,19073454,2025-11-27 00:06:20.323+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-65,NaN,60.234862,23.588156,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19073455,2025-11-27 00:06:21.841+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-58,NaN,60.235090,23.587418,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,19073456,2025-11-27 00:06:23.638+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-51,NaN,60.235293,23.586860,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19073457,2025-11-27 00:06:25.228+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-65,NaN,60.235455,23.586463,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19073458,2025-11-27 00:06:26.774+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-78,20106.0,60.235624,23.586074,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### ***Loading Data for button press on day 3***

In [4]:
csv_path_3 = r"C:\SUBASH\LAPIN_AMK\SPRING2026\PROJECT\EDA\Hazard_Situation_Analysis_and_Prediction\DATA\flic_button_data_export_20260109.csv"
df3 = pd.read_csv(csv_path_3)
df3.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,20045549,2026-01-09 01:16:43.519+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-70,NaN,60.463376,22.109561,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20045550,2026-01-09 01:16:45.393+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-59,20106.0,60.463308,22.109523,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20045551,2026-01-09 01:16:47.808+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-66,NaN,60.463243,22.109489,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,20045552,2026-01-09 01:16:50.341+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-63,NaN,60.463080,22.109335,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20045553,2026-01-09 01:16:52.207+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-61,NaN,60.462975,22.109186,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### ***Merge 3 DF and making one called "button_press_df"***

In [5]:
# Concatenate the dataframes

button_press_df = pd.concat(
    [df1, df2, df3],
    ignore_index=True
)

button_press_df.head()

,id,ts,ruuvi,aplicom,companyid,address,rssi,advdata,lat,lon,...,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
0,18615183,2025-11-10 01:50:40.22+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-60,NaN,60.493152,22.288016,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18615186,2025-11-10 01:50:42.122+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-63,NaN,60.493151,22.288017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,18615187,2025-11-10 01:50:44.1+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-76,NaN,60.493150,22.288017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18615189,2025-11-10 01:50:45.963+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-55,NaN,60.493148,22.288014,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18615192,2025-11-10 01:50:48.722+02,NaN,Aplicom A11 001,NaN,80E4DA7EC61B,-54,NaN,60.493146,22.288012,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### ***Shape***

In [6]:
button_press_df.shape

(890, 22)

### ***Describe***

In [7]:
button_press_df.describe()

,id,ruuvi,companyid,rssi,advdata,lat,lon,temperature,accx,accy,accz,battvoltage,txpower,movcounter,measseqnum,calibrated_accx,calibrated_accy,calibrated_accz
count,8.900000e+02,0.0,0.0,890.000000,52.0,890.000000,890.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,1.922144e+07,NaN,NaN,-64.996629,20106.0,60.293211,23.148509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,4.941914e+05,NaN,NaN,6.569263,0.0,0.146343,0.494796,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.861518e+07,NaN,NaN,-90.000000,20106.0,59.819271,22.103270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.907354e+07,NaN,NaN,-69.000000,20106.0,60.234854,22.940673,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.910362e+07,NaN,NaN,-65.000000,20106.0,60.246418,23.159413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.910536e+07,NaN,NaN,-60.000000,20106.0,60.406300,23.555303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2.006978e+07,NaN,NaN,-50.000000,20106.0,60.493152,23.772859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### ***Check for NaN***

In [8]:
button_press_df.isna().sum()

id                   0
ts                   0
ruuvi              890
aplicom              0
companyid          890
address              0
rssi                 0
advdata            838
lat                  0
lon                  0
geom                 0
temperature        890
accx               890
accy               890
accz               890
battvoltage        890
txpower            890
movcounter         890
measseqnum         890
calibrated_accx    890
calibrated_accy    890
calibrated_accz    890
dtype: int64

### ***Drop columns that are fully NaN***

In [9]:
button_press_df1 = button_press_df.dropna(axis=1, how="all")
button_press_df1.isna().sum()

id           0
ts           0
aplicom      0
address      0
rssi         0
advdata    838
lat          0
lon          0
geom         0
dtype: int64

In [10]:
button_press_df1.shape

(890, 9)

### ***lets drop "advdata" and see the shape***

In [11]:
# drop advdata column
button_press_df1 = button_press_df1.drop(columns=['advdata'])
button_press_df1.shape

(890, 8)

### ***new DF***

In [12]:
button_press_df1.head()

,id,ts,aplicom,address,rssi,lat,lon,geom
0,18615183,2025-11-10 01:50:40.22+02,Aplicom A11 001,80E4DA7EC61B,-60,60.493152,22.288016,0101000020E610000088B9A46ABB4936407FFACF9A1F3F...
1,18615186,2025-11-10 01:50:42.122+02,Aplicom A11 001,80E4DA7EC61B,-63,60.493151,22.288017,0101000020E610000029B16B7BBB493640AE7E6C921F3F...
2,18615187,2025-11-10 01:50:44.1+02,Aplicom A11 001,80E4DA7EC61B,-76,60.493150,22.288017,0101000020E610000029B16B7BBB493640DE02098A1F3F...
3,18615189,2025-11-10 01:50:45.963+02,Aplicom A11 001,80E4DA7EC61B,-55,60.493148,22.288014,0101000020E610000047CA1649BB4936403D0B42791F3F...
4,18615192,2025-11-10 01:50:48.722+02,Aplicom A11 001,80E4DA7EC61B,-54,60.493146,22.288012,0101000020E610000005DB8827BB4936409D137B681F3F...

### ***check for negative***

RSSI is signal strength so that it can be Negative

In [13]:
neg = (button_press_df1.select_dtypes(include='number') < 0).any()
pd.DataFrame(neg, columns=['Neg'])

        Neg
id    False
rssi   True
lat   False
lon   False

### ***check for Duplicates***

No Duplicates

In [14]:
button_press_df1.duplicated().sum()

np.int64(0)

### ***check for DatTypes***

We have Numeric & String Data. On the other hand we dont have any categorical data also

In [15]:
pd.DataFrame(button_press_df1.dtypes, columns=['Data Type'])

        Data Type
id          int64
ts            str
aplicom       str
address       str
rssi        int64
lat       float64
lon       float64
geom          str

In [16]:
button_press_df1.head()

,id,ts,aplicom,address,rssi,lat,lon,geom
0,18615183,2025-11-10 01:50:40.22+02,Aplicom A11 001,80E4DA7EC61B,-60,60.493152,22.288016,0101000020E610000088B9A46ABB4936407FFACF9A1F3F...
1,18615186,2025-11-10 01:50:42.122+02,Aplicom A11 001,80E4DA7EC61B,-63,60.493151,22.288017,0101000020E610000029B16B7BBB493640AE7E6C921F3F...
2,18615187,2025-11-10 01:50:44.1+02,Aplicom A11 001,80E4DA7EC61B,-76,60.493150,22.288017,0101000020E610000029B16B7BBB493640DE02098A1F3F...
3,18615189,2025-11-10 01:50:45.963+02,Aplicom A11 001,80E4DA7EC61B,-55,60.493148,22.288014,0101000020E610000047CA1649BB4936403D0B42791F3F...
4,18615192,2025-11-10 01:50:48.722+02,Aplicom A11 001,80E4DA7EC61B,-54,60.493146,22.288012,0101000020E610000005DB8827BB4936409D137B681F3F...

### ***We have Only one device type . So that we can remove it***

In [17]:
button_press_df1["aplicom"].nunique()

1

In [18]:
button_press_df1["aplicom"].value_counts()

aplicom
Aplicom A11 001    890
Name: count, dtype: int64

### ***We have Only one Address which is Device Identification Address like MAC Address for an example . So that we can remove it***

In [19]:
button_press_df1["address"].nunique()

1

In [20]:
button_press_df1["address"].value_counts()

address
80E4DA7EC61B    890
Name: count, dtype: int64